<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PacienteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('pacientes')->insert([
            [
                'dni' => '12345678',
                'nombres' => 'Juan',
                'apellidos' => 'Pérez',
                'fecha_nacimiento' => '1990-01-01',
                'genero' => 'Masculino',
                'celular' => '999123456',
                'email' => 'juan.perez@example.com',
                'tipo_sangre' => 'O+',
                'seguro_medico' => 'EsSalud',
                'estado' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'dni' => '87654321',
                'nombres' => 'María',
                'apellidos' => 'López',
                'fecha_nacimiento' => '1985-05-15',
                'genero' => 'Femenino',
                'celular' => '999876543',
                'email' => 'maria.lopez@example.com',
                'tipo_sangre' => 'A-',
                'seguro_medico' => 'Pacifico',
                'estado' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'dni' => '44556677',
                'nombres' => 'Alex',
                'apellidos' => 'García',
                'fecha_nacimiento' => '2000-07-10',
                'genero' => 'Otro',
                'celular' => '999445566',
                'email' => 'alex.garcia@example.com',
                'tipo_sangre' => 'AB+',
                'seguro_medico' => 'Rimac',
                'estado' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'dni' => '11223344',
                'nombres' => 'Carlos',
                'apellidos' => 'Gómez',
                'fecha_nacimiento' => '1978-09-23',
                'genero' => 'Masculino',
                'celular' => '999112233',
                'email' => 'carlos.gomez@example.com',
                'tipo_sangre' => 'B+',
                'seguro_medico' => null,
                'estado' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'dni' => '55667788',
                'nombres' => 'Lucía',
                'apellidos' => 'Torres',
                'fecha_nacimiento' => '1995-12-02',
                'genero' => 'Femenino',
                'celular' => '999556677',
                'email' => 'lucia.torres@example.com',
                'tipo_sangre' => 'O-',
                'seguro_medico' => 'Sanitas',
                'estado' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'dni' => '99887766',
                'nombres' => 'Roberto',
                'apellidos' => 'Sánchez',
                'fecha_nacimiento' => '1960-03-30',
                'genero' => 'Masculino',
                'celular' => '999998877',
                'email' => 'roberto.sanchez@example.com',
                'tipo_sangre' => 'A+',
                'seguro_medico' => 'EsSalud',
                'estado' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'dni' => '33445566',
                'nombres' => 'Elena',
                'apellidos' => 'Ramírez',
                'fecha_nacimiento' => '1992-08-14',
                'genero' => 'Femenino',
                'celular' => '999334455',
                'email' => 'elena.ramirez@example.com',
                'tipo_sangre' => 'B-',
                'seguro_medico' => null,
                'estado' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'dni' => '22334455',
                'nombres' => 'Jordan',
                'apellidos' => 'Méndez',
                'fecha_nacimiento' => '1998-11-20',
                'genero' => 'Otro',
                'celular' => '999223344',
                'email' => 'jordan.m@example.com',
                'tipo_sangre' => 'AB-',
                'seguro_medico' => 'Mapfre',
                'estado' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'dni' => '77665544',
                'nombres' => 'Ricardo',
                'apellidos' => 'Castro',
                'fecha_nacimiento' => '1988-04-05',
                'genero' => 'Masculino',
                'celular' => '999776655',
                'email' => 'ricardo.c@example.com',
                'tipo_sangre' => 'O+',
                'seguro_medico' => 'Pacifico',
                'estado' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'dni' => '66554433',
                'nombres' => 'Sofia',
                'apellidos' => 'Herrera',
                'fecha_nacimiento' => '2005-01-12',
                'genero' => 'Femenino',
                'celular' => '999665544',
                'email' => 'sofia.h@example.com',
                'tipo_sangre' => 'A+',
                'seguro_medico' => 'Rimac',
                'estado' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
